### ISSUE TITLE
erroring out with plmn 001001 or 00101

### ISSUE THREAD

**Issue by pcw11211** [fasferraz/eNB#9]
when using with plmn 001001 or with plmn 00101 i get following error:
```
Returning PLMN from: 001001
Traceback (most recent call last):
  File "/home/admin/eNB/eNB_LOCAL.py", line 2704, in <module>
    main()
  File "/home/admin/eNB/eNB_LOCAL.py", line 2630, in main
    session_dict = session_dict_initialization(session_dict)
  File "/home/admin/eNB/eNB_LOCAL.py", line 188, in session_dict_initialization
    session_dict['ENCODED-GUTI'] = eNAS.encode_guti(int(session_dict['PLMN']),32769,1,12345678)
  File "/home/admin/eNB/eNAS.py", line 1156, in encode_guti
    guti += unhexlify(mcc_mnc[1] + mcc_mnc[0] + mcc_mnc[5] +mcc_mnc[2]+ mcc_mnc[4]+ mcc_mnc[3])
IndexError: string index out of range
```

to resolve it i added before line 1155:
    if len(mcc_mnc) == 3: mcc_mnc += 'f'
    if len(mcc_mnc) == 4: mcc_mnc += 'f'

diff:
```diff --git a/eNAS.py b/eNAS.py
index 05fe379..221742d 100644
--- a/eNAS.py
+++ b/eNAS.py
@@ -1152,6 +1152,8 @@ def encode_guti(mcc_mnc, mme_group_id, mme_code, m_tmsi):
     guti = b'\xf6'
     mcc_mnc = str(mcc_mnc)

+    if len(mcc_mnc) == 3: mcc_mnc += 'f'
+    if len(mcc_mnc) == 4: mcc_mnc += 'f'
     if len(mcc_mnc) == 5: mcc_mnc += 'f'
     guti += unhexlify(mcc_mnc[1] + mcc_mnc[0] + mcc_mnc[5] +mcc_mnc[2]+ mcc_mnc[4]+ mcc_mnc[3])
     guti += struct.pack("!H", mme_group_id)
```

PS thank you for your awesome code

**Comment by fasferraz** [comment]
the problem is that i do this when i call GUTI:
```
int(session_dict['PLMN'])
```

so '00101' turns 101, and then inside enconde_guti i turn the variable again to string. I will remove the integer, that will solve the  issue.

**Comment by fasferraz** [comment]
Correction done. Please test and report please
